### ISSUE TITLE
In file 1m-go-websockets/1_ws_example/client.go line 25 

### ISSUE THREAD

**Issue by shooyaaa** [eranyanay/1m-go-websockets#1]
172.17.0.1 should be 127.0.0.1

**Comment by eranyanay** [comment]
Thanks @shooyaaa, however this and the rest of the examples are meant to be ran on an environment with Docker (which is also the environment used to run it during the talk)
Hence the hard-coded 172.17.0.1, the default subnet for Docker network

**Comment by eranyanay** [comment]
@shooyaaa added parameter with default value, see latest commit
