### ISSUE TITLE
In production, EACH CLIENT (IP) IS DIFERENT, ¿can more than 65k connections be achieved? without using setup.sh

### ISSUE THREAD

**Issue by jerber123** [eranyanay/1m-go-websockets#12]
Hi, thanks for the code, I am implementing a chat application (similar to tawk.to, phplivesupport, livechat, livechatinc, etc ...), and I have a question, testing from a single client (ip) and without using setup.sh (go run client.go -conn=100000) (with server 4_optimize_gobwas) only about 65k connections can be made for the limits of the ports. In production, EACH CLIENT (IP) IS DIFERENT, ¿can more than 65k connections be achieved?

**Comment by eranyanay** [comment]
Yes the limitation you are facing is from the client side, because you cannot open more than concurrent 65K connections on a single host.
This is why the demo uses docker to achieve more than 65K conns on a single machine

**Comment by jerber123** [comment]
Thank you very much
