### ISSUE TITLE
Question about kqueue. When are the e.changes and e.connections decreased?

### ISSUE THREAD

**Issue by ytkang** [eranyanay/1m-go-websockets#14]
https://github.com/eranyanay/1m-go-websockets/blob/master/4_optimize_gobwas/kqueue_darwin.go

in this code, I cannot find any deleting element from e.changes and e.connections

**Comment by eranyanay** [comment]
@ytkang suggest to communicate this with @sc0Vu, as he pushed the kqueue implementation.
I do not have mac box to test/fix it myself.
