### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by imawhale** [eranyanay/1m-go-websockets#15]
Thank you for your talk at GoCon and for publishing this repo.

I get this error when running 4_optimize_gobwas `go run server.go`

```
./server.go:13:22: undefined: eventsCollector
./server.go:47:25: undefined: MkEventsCollector
```

**Comment by eranyanay** [comment]
@imawhale You need to properly compile it with all the dependencies.
Please try 
`go build server.go epoll.go kqueue_darwin.go`
