### ISSUE TITLE
kqueue implementation broken

### ISSUE THREAD

**Issue by christian-ehmig** [eranyanay/1m-go-websockets#16]
Hi,
although few are running servers on Darwin, one might like to run a test on a local machine. Seems like your kqueue implementation waits forever without accepting new events.

In line https://github.com/eranyanay/1m-go-websockets/blob/master/4_optimize_gobwas/kqueue_darwin.go#L77
you pass "nil" as timeout to syscall.Kevent. This call blocks forever, since e.changes points to the initially empty slice. Although new connections will be added to e.changes, Kevent will never pick them up.

Fix with
```
var ts syscall.Timespec
n, err := syscall.Kevent(e.fd, e.changes, events, &ts)
```

A proper timeout should be set, otherwise you'll run into high CPU usage this way.

**Comment by eranyanay** [comment]
Thank you @christian-ehmig 
The kqueue example was added by @sc0Vu, perhaps he can assist.
I do not use mac and cannot test it

**Comment by eranyanay** [comment]
At the moment I'm considering removing it completely, I dont see the usecase for this repo for darwin anyway, it doesn't seem to work once a client disconnects, and if @sc0Vu isn't planning to fix, I will send a PR and remove it entirely

**Comment by christian-ehmig** [comment]
Sure, no objections.

**Comment by eranyanay** [comment]
Great, thank you @christian-ehmig
