### ISSUE TITLE
defer in for  have  Performance problems

### ISSUE THREAD

**Issue by hauson** [eranyanay/1m-go-websockets#17]
the code where in client.go,  ‘defer’ statements was inner of 'for',  defer statements have extra operations, this could have  have  Performance problems.

**Comment by eranyanay** [comment]
thanks @hauson, but Im closing this issue
The client is not meant to be highly optimized, it is used only as a tool to demonstrate/benchmark
It has other flaws, such as low rate of message handling when opening many connections
