### ISSUE TITLE
Gorilla optimzations

### ISSUE THREAD

**Issue by stevenscott89** [eranyanay/1m-go-websockets#3]
Use [Upgrader.WriteBufferPool](https://godoc.org/github.com/gorilla/websocket#Upgrader.WriteBufferPool) to reduce allocations of write buffers: 

```
var upgrader = websocket.Upgrader{WriteBufferPool: &sync.Pool{}}

func ws(w http.ResponseWriter, r *http.Request) {
	// Upgrade connection
	conn, err := upgrader.Upgrade(w, r, nil)
        ...
```

Return from HTTP handler to release memory held by the net/http package:

```
var upgrader = websocket.Upgrader{WriteBufferPool: &sync.Pool{}}

func ws(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		return
	}
        go func() {
	    // Read messages from socket
	    for {
		_, msg, err := conn.ReadMessage()
		if err != nil {
			conn.Close()
			return
		}
		log.Printf("msg: %s", string(msg))
	    }
        }()
}
```

Use reasonable size for read buffer.  A 256 byte buffer is large enough to read an entire message sent by the example client and uses 1/16 the memory of the default.  

```
var upgrader = websocket.Upgrader{WriteBufferPool: &sync.Pool{}, ReadBufferSize: 256}
...
```

Call [Conn.UnderlyingConn](https://godoc.org/github.com/gorilla/websocket#Conn.UnderlyingConn) to get the underlying network connection instead of using [reflection](https://github.com/eranyanay/1m-go-websockets/blob/3a7edcc60fae4cd2d46fd15908fb9f4bcff9c49a/3_optimize_ws_goroutines/epoll.go#L77).

**Comment by eranyanay** [comment]
Thanks @stevenscott89 
This could be a nice extra step between the optimizations, but it takes an assumption on the input size, something I rather not have in the shown examples
I agree that the suggestion works for the given example, but the client is just an example and the server is generic

Re UnderlyingConn, I not only take the underlying connection, I take the file descriptor which is not exposed in any way by the interface or the struct itself. Hence the reflection

**Comment by stevenscott89** [comment]
You did not address my first two points in your response (use pool to eliminate memory overhead of write buffer, return from HTTP hander to release memory used by net/http package).

The buffer sizes allow an application to tradeoff memory use for system calls.  Smaller buffers can increase the number of system calls to read or write a message. Larger buffers obviously use more memory.  The buffer size does not limit the size of a message.

The code in this repo uses a read buffer size of 4096 bytes. This is large for both the actual benchmark and typical applications. 

The fact that you need to use reflection to dig the fd out of the net.Conn is not a reason to use reflection to dig through the Gorilla connection.  Gorilla provided an API for this purpose.
